### ISSUE TITLE
example file not working

### ISSUE THREAD

**Issue by roni-kemp** [murthylab/sleap-notebooks#3]
Hi, there is a problem with "Training and inference using Google Drive" when running this line:
`!sleap-train baseline.bottomup.json colab.pkg.slp --run_name "colab_demo.bottomup"`

you get this error:
`Traceback (most recent call last):
  File "/usr/local/bin/sleap-train", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/sleap/nn/training.py", line 1328, in main
    raise FileNotFoundError(f"Could not find training profile: {job_filename}")
FileNotFoundError: Could not find training profile: baseline.bottomup.json
`

seems like the problem is a renaming of the baseline.bottomup.json file which was done at this commit:
704047c65acf1855545b0218e3a601c953a4b16e

guess the new line should read:
`!sleap-train baseline_medium_rf.bottomup.json colab.pkg.slp --run_name "colab_demo.bottomup"`

**Comment by talmo** [comment]
Hi @roni-kemp,

Thanks for pointing this out! Yes, we had to update the notebooks for SLEAP v1.0.10. They should be working now.

Cheers!

Talmo
